# Generate checkout-based units without Qt or compiler discovery.
get_filename_component(COTTO_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(COTTO_NATIVE "${CMAKE_CURRENT_BINARY_DIR}/sotto-linux")
set(COTTO_DEFAULT_CONFIG_HOME "$ENV{HOME}/.config")
if(IS_ABSOLUTE "$ENV{XDG_CONFIG_HOME}")
    set(COTTO_DEFAULT_CONFIG_HOME "$ENV{XDG_CONFIG_HOME}")
endif()
# PATH cache entries normalize backslashes, which are valid Linux filename bytes.
set(COTTO_QT_CONFIG_HOME "${COTTO_DEFAULT_CONFIG_HOME}" CACHE STRING "Existing cotto Qt configuration root")
set(COTTO_SETTINGS "${COTTO_QT_CONFIG_HOME}")
foreach(value COTTO_ROOT COTTO_NATIVE COTTO_SETTINGS)
    string(REPLACE "\\" "\\\\" ${value} "${${value}}")
    string(REPLACE "\"" "\\\"" ${value} "${${value}}")
    string(REPLACE "%" "%%" ${value} "${${value}}")
    if("${${value}}" MATCHES "[\n\r]")
        message(FATAL_ERROR "Startup configuration must not contain line breaks")
    endif()
endforeach()
# ExecStart expands dollars; Environment does not.
string(REPLACE "$" "$$" COTTO_ROOT "${COTTO_ROOT}")
string(REPLACE "$" "$$" COTTO_NATIVE "${COTTO_NATIVE}")
configure_file("${CMAKE_CURRENT_LIST_DIR}/../resources/cotto.service.in" cotto.service @ONLY)
configure_file("${CMAKE_CURRENT_LIST_DIR}/../resources/cotto-inference.service.in" cotto-inference.service @ONLY)
